### ISSUE TITLE
[Feature]: Category Sort priority

### ISSUE THREAD

**Issue by Suddow** [Cidan/BetterBags#383] opened 2024-05-24 18:02 UTC
### Describe the feature

Please bring back category sorting that adibags had.  For example, grouping equipment together, consumables together, etc.  Currently betterbags will only sort at a global level.

### Describe the implementation

Same category sorting that was available for adibags.  The specific option was "By Category, subcategory, quality and item level (default)".

**Comment by Cidan** [comment] 2024-05-25 23:02
Duplicate of #189

**Closed by Cidan** 2024-05-25 23:02 UTC
Labels: triage, feature
