### ISSUE TITLE
make bag position unique for each character

### ISSUE THREAD

**Issue by G1ak1** [Cidan/BetterBags#456] opened 2024-07-03 16:12 UTC
### Describe the feature

hey. would be amazing to make the bag position unique for each character. not all of them have the same bags so its changing position based on which char ui moved it and its really frustrating when u got ur ui sorted. can u pls add that? 

thank u

### Describe the implementation

make each character bag position unique

**Comment by Cidan** [comment] 2024-07-03 16:40
Duplicate of #377

**Closed by Cidan** 2024-07-03 16:40 UTC
Labels: triage, feature
