### ISSUE TITLE
[Feature]: Reorder Categories

### ISSUE THREAD

**Issue by mattlinsky** [Cidan/BetterBags#256] opened 2024-02-29 01:00 UTC
### Describe the feature

Be able to reorder categories. For example, Personally I would like gear sets first, in alphabetical order, then consumables, followed by random categories, with miscellaneous stuff last

### Describe the implementation

2 options. One I think would easier for some people would be to have an edit mode for bags and be able to drag categories around and it would remember your settings. The second option would be to go into betterbag options and have another area there where you can set things there. You already have a spot for section sorting so maybe take that out of the backpack settings and give it it's own subsection

**Comment by Cidan** [comment] 2024-02-29 01:01
Duplicate of #189

**Closed by Cidan** 2024-02-29 01:01 UTC
Labels: triage, feature
