### ISSUE TITLE
Classic SoM - Can't see keychain in normal view

### ISSUE THREAD

**Issue by fireboy92k** [Cidan/BetterBags#544] opened 2024-08-05 23:33 UTC
### Addon Version

v1.89

### World of Warcraft Version

Classic Era (And SoD/Hardcore)

### Describe the bug

The normal bag view does not show the keyring.  Clicking on the keyring button brings up the entire bag UI without the keychain.  I can change to the 'show bags view' which shows the keyring as bag 6.  Normally wouldn't be a big deal, since keys unlock dungeons by default.  But in SoM you can put items you need on the keychain like the Beacon of Hydraxis.

### Steps to reproduce

click on keychain icon, observe bags open but you can't see the keychain.  Select the 'show bags' option from the bag menu, observe that the keychain is Bag 6.

![image](https://github.com/user-attachments/assets/de115253-1f33-402c-a9dc-485fb62fb806)

**Comment by AMaribo** [comment] 2024-08-06 00:19
Duplicate of #469

**Closed by AMaribo** 2024-08-06 00:19 UTC
Labels: bug, triage

**Comment by fireboy92k** [comment] 2024-08-06 00:23
Not exactly.  That one says you can't see the SoM items in the keyring.  This bug is that clicking the keyring on the main UI doesn't open the keyring at all.  I can get to it by going to the Show Bags Option, but I can't see the keyring in the normal bag manu without it at all.

**Comment by AMaribo** [comment] 2024-08-06 02:38
Sorry about that. I was focusing on the Beacon of Hydraxis portion.
The keyring not appearing in the bags unless you're in Show Bags view is currently a known feature, but usable items, such as the Beacon of Hydraxis or other cosmetic items, should be viewable in some manner other than having to Show Bags.

**Comment by fireboy92k** [comment] 2024-08-06 03:37
Gotcha.  Yeah, I guess one or the other would work for sure.  Used to AdiBags just showing a special pop up for just the keyring.  But would be nice to have a SoM overlay of come sort for the specific items.  Though that seems like a loosing battle if Blizz keeps adding more and more keyring items!
