### ISSUE TITLE
[Feature]: Minimize/Hide categories

### ISSUE THREAD

**Issue by xCrowth** [Cidan/BetterBags#630] opened 2024-08-24 13:58 UTC
### Describe the feature

I would like to be able to Minimize and / or Hide categories in order to have a cleaner look on my bags and be able to quickly identify the items I am interested in.

### Describe the implementation

This could be done in several ways, an example would be to left click on the category and have it minimized (or any other shortcut), the same with hiding.

In the case of minimized I would like for the categories to still be visible in the bags and in the case of Hidden categories maybe could be an option in the already created "Configure Categories" to show them again.

To add more features to it, maybe an option to show the minimized/hidden categories on vendor/bank would be nice.

What do you think about it?

**Comment by AMaribo** [comment] 2024-08-24 14:01
Minimizing categories (as in keeping the category name visible, but hiding the items) is not available currently, but hiding categories is.
Open up `Configure Categories`, then right click on the category you want to hide.

**Comment by xCrowth** [comment] 2024-08-24 16:35
The feature as it is right now, only hiding without any additional options, makes it unlikely to be used as it would need several clicks to hide and unhide every time you want to sell / move items in bank, etc. while the minimised allows to make this easy (or implement a shortcut or something to hide/unhide the "hide category" selected) can you reconsider this?

**Comment by AMaribo** [comment] 2024-08-24 17:29
I will reopen this feature request, but let you know that Cidan has talked about it in Discord and said that he is on the fence for collapsing sections. [Relevant Discord conversation](https://discord.com/channels/1063213796845428876/1063213797633966122/1271967743255515287)
His main concerns are how to make it look good and useable without shifting everything in the bag every time you collapse and expand sections.

**Comment by xCrowth** [comment] 2024-08-24 17:37
I understand, if that is the case maybe it is easier to make the Hiding functionality more usable through shortcuts (show/hide hidden sections) or options to see these sections easily under certain conditions (sell/bank/auction/etc.)

**Comment by zeptognome** [comment] 2024-08-24 19:25
I also think this is a good feature request (one I made months ago)
What I was thinking is a category title click (modifier probably) would replace the item icons with a virtual stack of sorts showing a generic icon (the BetterBags logo?) and a count

Right now, 'hidden' is not a good option for me as I don't remember if I hid all my tradeskill items when I logged out or left them in the bank.. having a minimal visual reminder would be better for me.

**Comment by AMaribo** [comment] 2024-08-24 19:28
Checking through the issues, this is also a duplicate of #73

**Comment by Cidan** [comment] 2024-08-24 21:36
Duplicate of #73 -- this is pending some other work that is blocking it + design review.

**Closed by Cidan** 2024-08-24 21:36 UTC
Labels: triage, feature
