### ISSUE TITLE
[Feature Req] Import Adibags custom categories

### ISSUE THREAD

**Issue by rodalpho** [Cidan/BetterBags#112] opened 2024-02-19 14:27 UTC
I have *extensive* custom categories setup over the years, all clicky items in one bucket, putting the various items for each patch into its own separate bucket, rep tokens by rep, etc. If possible, would be great if they could be imported from Adibags so I don't need to rebuild them.

**Comment by Cidan** [comment] 2024-02-21 04:28
Duplicate of #122

**Closed by Cidan** 2024-02-21 04:28 UTC
Labels: triage
