### ISSUE TITLE
[Feature]: Drag and drop items on Category to add to filter

### ISSUE THREAD

**Issue by woodrikj** [Cidan/BetterBags#148] opened 2024-02-19 20:34 UTC
### Describe the feature

Drag and drop items on Category to add to filter inside the bags window without opening config panel 

### Describe the implementation

Drag and drop items on Category to add to filter inside the bags window without opening config panel

**Comment by Cidan** [comment] 2024-02-19 20:43
Duplicate of #109

**Closed by Cidan** 2024-02-19 20:43 UTC
Labels: triage, feature
