### ISSUE TITLE
Error displaying the icon of bags by the Bartender 

### ISSUE THREAD

**Issue by Louivatar** [Cidan/BetterBags#322] opened 2024-04-07 10:26 UTC
### Addon Version

v0.1.all

### World of Warcraft Version

Retail

### Describe the bug

There is an error with displaying the icon of the combined bags with displaying the bag of reagents with a separate icon by the Bartender add-on when the BetterBag add-on is enabled. The icon of the reagent bag disappears, and the icon of the combined bags goes out of the field

### Steps to reproduce

1. The Bartender is configured as in screenshot 1
![01](https://github.com/Cidan/BetterBags/assets/132486656/b6017128-de74-40e9-9cbc-c668b7ad185c)
2. The display gets up normally - screenshot 2
![02](https://github.com/Cidan/BetterBags/assets/132486656/552d9c9d-9369-47df-b728-c1aedfe38c1d)
3. After restarting, the icon of the reagent bag disappears, the icon of the combined bag moves out of the field - screenshot 3
![03](https://github.com/Cidan/BetterBags/assets/132486656/fe771d7b-5191-43e1-b4e4-944f38a41ebe)

**Comment by Cidan** [comment] 2024-04-10 20:39
Duplicate of #190

**Closed by Cidan** 2024-04-10 20:39 UTC
Labels: bug, triage
