### ISSUE TITLE
[Feature]: Assign Category to Top of Bags 

### ISSUE THREAD

**Issue by justaround31** [Cidan/BetterBags#328] opened 2024-04-13 17:07 UTC
### Describe the feature

It would be cool to be able to assign a category to the top of a bag in position 1, 2, or 3.
I always have to scan my bags for the hearthstone and its in a different place in the bags all the time depending on what I am  carrying.

### Describe the implementation

Just a request. I have no request on where this should go.

**Comment by Cidan** [comment] 2024-04-13 17:07
Duplicate of #189

**Closed by Cidan** 2024-04-13 17:07 UTC
Labels: triage, feature
