### ISSUE TITLE
[Feature]: Drop the split of a stack anywhere in the bag

### ISSUE THREAD

**Issue by juntereiner** [Cidan/BetterBags#529] opened 2024-08-02 23:57 UTC
### Describe the feature

Right now, if I want to split a stack of something, I need to drop it in the free space of the bag. That's a bit inconvenient. I should be able to drop it anywhere in the bag window.

### Describe the implementation

When I split a stack of something like herbs, I can drop the new stack anywhere in the bag.

**Comment by zeptognome** [comment] 2024-08-03 00:31
duplicate of https://github.com/Cidan/BetterBags/issues/418

**Closed by zeptognome** 2024-08-03 00:31 UTC
Labels: triage, feature
