### ISSUE TITLE
Blizzard Bag Button Not Showing

### ISSUE THREAD

**Issue by SargonStarblade** [Cidan/BetterBags#369] opened 2024-05-12 03:19 UTC
### Addon Version

10.2.7

### World of Warcraft Version

Retail

### Describe the bug

On log in the Blizzard bag button is not showing. I have selected to show the bag button in BetterBags. I am not sure if it is a bug with BetterBags or an interaction with another addon. If I disable BetterBags the Blizzard bag button is back. I can temporarily get around the bug by opening Bartender4, clicking to not show the bag bar, then clicking to show it again. This however needs to be repeated at every log in or character switch.

### Steps to reproduce

Log in to WoW.

**Comment by SargonStarblade** [comment] 2024-05-12 03:24
I just tried loading without Bartender4 and with BetterBags. The bag bar was back. I think the problem is an interaction between both addons.

**Comment by zeptognome** [comment] 2024-05-12 03:49
Duplicate of #190  

Solution for now is to move BT4's bag bar 64 pixels further left than you want the bag to end up.

**Comment by AMaribo** [comment] 2024-07-30 21:54
Duplicate of #190

**Closed by AMaribo** 2024-07-30 21:54 UTC
Labels: bug, triage
