### ISSUE TITLE
Bag contents show on screen when potion used in m+

### ISSUE THREAD

**Issue by ddel641** [Cidan/BetterBags#160] opened 2024-02-20 03:19 UTC
### Addon Version

v0.1.5

### World of Warcraft Version

Retail

### Describe the bug

When running a Mythic + dungeon and using a potion from the hot bar the bag screen bugs and shows a large version of the bag on the screen regardless of interface being open. This only happens when in combat. It does not seem to happen in combat in other locations. Attached image shows what I am talking about. 

Errors grabed from bugsack: 

> 4x ..FrameXML/ObjectAPI/ContinuableContainer.lua:85: script ran too long
> [string "@FrameXML/ObjectAPI/ContinuableContainer.lua"]:85: in function <..FrameXML/ObjectAPI/ContinuableContainer.lua:75>
> [string "=(tail call)"]: ?
> [string "@BetterBags/data/items.lua"]:166: in function `ProcessContainer'
> [string "@BetterBags/data/items.lua"]:160: in function `RefreshBackpack'
> [string "@BetterBags/data/items.lua"]:99: in function `RefreshAll'
> [string "@BetterBags/data/items.lua"]:64: in function `cb'
> [string "@BetterBags/core/events.lua"]:113: in function <BetterBags/core/events.lua:108>
> 
> Locals:
> Skipped (In Encounter)
> 

> 4x ...Ons/Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua:20: script ran too long
> [string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:20: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
> [string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
> [string "@BetterBags/core/events.lua"]:129: in function `SendMessage'
> [string "@BetterBags/data/items.lua"]:172: in function <BetterBags/data/items.lua:166>
> [string "=[C]"]: in function `xpcall'
> [string "@FrameXML/ObjectAPI/ContinuableContainer.lua"]:83: in function <..FrameXML/ObjectAPI/ContinuableContainer.lua:75>
> [string "=(tail call)"]: ?
> [string "@BetterBags/data/items.lua"]:166: in function `ProcessContainer'
> [string "@BetterBags/data/items.lua"]:160: in function `RefreshBackpack'
> [string "@BetterBags/data/items.lua"]:99: in function `RefreshAll'
> [string "@BetterBags/data/items.lua"]:64: in function `cb'
> [string "@BetterBags/core/events.lua"]:113: in function <BetterBags/core/events.lua:108>
> 
> Locals:
> Skipped (In Encounter)

> 3x BetterBags/frames/column.lua:61: script ran too long
> [string "@BetterBags/frames/column.lua"]:61: in function `RemoveAll'
> [string "@BetterBags/frames/grid.lua"]:147: in function `Draw'
> [string "@BetterBags/views/gridview.lua"]:186: in function `Render'
> [string "@BetterBags/frames/bag.lua"]:204: in function `Draw'
> [string "@BetterBags/core/init.lua"]:139: in function `cb'
> [string "@BetterBags/core/events.lua"]:45: in function <BetterBags/core/events.lua:40>
> [string "=[C]"]: ?
> [string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
> [string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
> [string "@BetterBags/core/events.lua"]:129: in function `SendMessage'
> [string "@BetterBags/data/items.lua"]:172: in function <BetterBags/data/items.lua:166>
> [string "=[C]"]: in function `xpcall'
> [string "@FrameXML/ObjectAPI/ContinuableContainer.lua"]:83: in function <..FrameXML/ObjectAPI/ContinuableContainer.lua:75>
> [string "=(tail call)"]: ?
> [string "@BetterBags/data/items.lua"]:166: in function `ProcessContainer'
> [string "@BetterBags/data/items.lua"]:160: in function `RefreshBackpack'
> [string "@BetterBags/data/items.lua"]:99: in function `RefreshAll'
> [string "@BetterBags/data/items.lua"]:64: in function `cb'
> [string "@BetterBags/core/events.lua"]:113: in function <BetterBags/core/events.lua:108>
> 
> Locals:
> Skipped (In Encounter)\

> 1x BetterBags/frames/column.lua:30: script ran too long
> [string "@BetterBags/frames/column.lua"]:30: in function `AddCell'
> [string "@BetterBags/frames/grid.lua"]:183: in function `Draw'
> [string "@BetterBags/views/gridview.lua"]:186: in function `Render'
> [string "@BetterBags/frames/bag.lua"]:204: in function `Draw'
> [string "@BetterBags/core/init.lua"]:139: in function `cb'
> [string "@BetterBags/core/events.lua"]:45: in function <BetterBags/core/events.lua:40>
> [string "=[C]"]: ?
> [string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
> [string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
> [string "@BetterBags/core/events.lua"]:129: in function `SendMessage'
> [string "@BetterBags/data/items.lua"]:172: in function <BetterBags/data/items.lua:166>
> [string "=[C]"]: in function `xpcall'
> [string "@FrameXML/ObjectAPI/ContinuableContainer.lua"]:83: in function <..FrameXML/ObjectAPI/ContinuableContainer.lua:75>
> [string "=(tail call)"]: ?
> [string "@BetterBags/data/items.lua"]:166: in function `ProcessContainer'
> [string "@BetterBags/data/items.lua"]:160: in function `RefreshBackpack'
> [string "@BetterBags/data/items.lua"]:99: in function `RefreshAll'
> [string "@BetterBags/data/items.lua"]:64: in function `cb'
> [string "@BetterBags/core/events.lua"]:113: in function <BetterBags/core/events.lua:108>
> 
> Locals:
> Skipped (In Encounter)

![WoWScrnShot_021924_215627](https://github.com/Cidan/BetterBags/assets/26681549/39b4e873-b91e-4b9e-8a63-a1d236eb1883)

### Steps to reproduce

1. Run  23 BRH or 22 TOTT as a resto druid (could happen in other keys as well)
2. Use Potion using keybind from hot key.

**Comment by Cidan** [comment] 2024-02-20 03:20
Duplicate of #128 -- actively working on this as priority 1.

**Closed by Cidan** 2024-02-20 03:20 UTC
Labels: bug, triage
