### ISSUE TITLE
Non-key items in keyring are not displayed in bag

### ISSUE THREAD

**Issue by DJSchaffner** [Cidan/BetterBags#572] opened 2024-08-12 16:58 UTC
### Addon Version

v0.1.91

### World of Warcraft Version

Classic Era (And SoD/Hardcore)

### Describe the bug

This might be an SoD only thing, but there are some vanity items that go into the keyring and are not displayed in bag unless showing all bags

![grafik](https://github.com/user-attachments/assets/da565f7a-a552-435c-a352-81244bb453ed)
Rainbow Generator and Beacon of Hydraxis for example

### Steps to reproduce

- Acquire item which is placed in keyring but is a usable item
- Try to find it in bag

**Comment by AMaribo** [comment] 2024-08-17 23:33
Duplicate of #469

**Closed by AMaribo** 2024-08-17 23:33 UTC
Labels: bug, triage
