### ISSUE TITLE
Custom Category Names, Fields (this one is a head spinner for me)

### ISSUE THREAD

**Issue by felbloodguy** [Cidan/BetterBags#195] opened 2024-02-21 18:36 UTC
### Addon Version

v0.1.7

### World of Warcraft Version

Retail

### Describe the bug

Many items (regardless of any existing Blizzard taxonomy, as far as I can tell) cannot be added by dragging and dropping. They can, however, be added to custom categories that already have items in them.

At first, I thought this had to be a tooltip/elvUI/install thing; now and again, I could get a Lua Error to throw. But that was this bug.
 

![image](https://github.com/Cidan/BetterBags/assets/160766297/6b80fcbf-32e0-4df5-bc08-1eeaf51bfbd0)
<details><summary>Details</summary>
<p>
Message: ...erface/AddOns/ElvUI/Core/Modules/Tooltip/Tooltip.lua:901: bad argument #1 to 'strmatch' (string expected, got nil)<l>
Time: Wed Feb 21 11:20:15 2024<l>
Count: 16<l>
Stack: ...erface/AddOns/ElvUI/Core/Modules/Tooltip/Tooltip.lua:901: bad argument #1 to 'strmatch' (string expected, got nil)<l>
[string "=[tsm error check]"]:1: in main chunk<l>
[string "=(tail call)"]: ?<l>
[string "=[C]"]: ?<l>
[string "=[C]"]: ?<l>
[string "@Interface/AddOns/ElvUI/Core/Modules/Tooltip/Tooltip.lua"]:901: in function <l><...erface/AddOns/ElvUI/Core/Modules/Tooltip/Tooltip.lua:898><newline>
[string "=(tail call)"]: ?<p>
[string "=[C]"]: in function `SetCurrencyToken'<newline>
[string "@Interface/AddOns/BetterBags/frames/currency.lua"]:85: in function <newline><Interface/AddOns/BetterBags/frames/currency.lua:83><newline>
</p>
</details> 

The odd thing is that items that could be added first to other categories cannot be added to 

I've tested renaming categories to irrelevant things outside of any BlizzardDB taxonomy,

It depends not just on the item but the category created and when that category was created. For instance, a category that works can be made after one that doesn't, where a previously immovable item can be moved into the category.

It appears that there's an issue with the category initialization in the Lua script. It could be that some data type parameter is not matching up, could be the dreaded missing parenthesis, or some other syntax disagreement. Hell, just two simple guesses, as I haven't had a chance to look under the hood.

Hope I get a cookie for doing all this work.

### Steps to reproduce

Create custom category
try to grab and drop from any source to the field indicated
enjoy watching your brain explode as you test items endlessly to figure this out (this was me), I'm hoping you'll have an easy time with some pointers.

**Comment by felbloodguy** [comment] 2024-02-21 18:40
<details><summary>Details</summary>
<p>

critical usability flaw

</p>
</details>

**Comment by Cidan** [comment] 2024-02-23 06:00
Duplicate of #129

**Closed by Cidan** 2024-02-23 06:00 UTC
Labels: bug, triage
