### ISSUE TITLE
[Feature]: Background color

### ISSUE THREAD

**Issue by I-AM-T3X** [Cidan/BetterBags#199] opened 2024-02-22 04:48 UTC
### Describe the feature

I love the background color of original adibags, where could I find it in the code to change it to that color

### Describe the implementation

I love the background color of original adibags, where could I find it in the code to change it to that color

**Comment by Cidan** [comment] 2024-02-22 19:42
Duplicate of #137

**Closed by Cidan** 2024-02-22 19:42 UTC
Labels: triage, feature
