### ISSUE TITLE
[Feature]: Add Possible way to show Other Characters/Guild-/Bank

### ISSUE THREAD

**Issue by Serverfrog** [Cidan/BetterBags#453] opened 2024-07-01 13:11 UTC
### Describe the feature

The Possibility to view the content of other Characters, their Bank and the GuildBank of them.
It is only possible to view the Content of things like Guild Bank, like how it was the last time you saw them, sure.

### Describe the implementation

This could be done, by saving/caching the content of the different Inventories in the Account Settings Area. With this is should be able to looked up and replace the Content of the Current Bag, with this content.

Yes i got this idea from ArkInventory ;)

**Comment by Cidan** [comment] 2024-07-02 05:29
Duplicate of #26

**Closed by Cidan** 2024-07-02 05:29 UTC
Labels: triage, feature
