### ISSUE TITLE
Missing Items Until Reload performed

### ISSUE THREAD

**Issue by honeydrake** [Cidan/BetterBags#333] opened 2024-04-16 16:17 UTC
### Addon Version

v0.1.27

### World of Warcraft Version

Retail

### Describe the bug

3 times now I have looted items (either from bodies or by crafting) and when I open my bag I cannot find them. Using the search feature built in cannot find them either.  But my TSM addon shows they are in my inventory.  Simply performing a /reload fixes the issue and they can now be found by me and the search feature.

### Steps to reproduce

1. Open the bag after looting (in this case crafting items in Valdrakken)
2. The two items this happened with today were a recently crafted Jeweled Offering and one specific Verdant Combatant's Jeweled Signet - even though the other 2 signets crafted at the same time showed up in the bags just fine.
3. Search feature cannot even find them.
4. Typing in /reload fixed the issue.

**Comment by honeydrake** [comment] 2024-04-16 17:28
I just recalled what the first item was last week that did this. It was Barter Bricks

**Comment by Frici42** [comment] 2024-04-16 20:38
I've also been getting this with various items but have not figured exactly when it happens to look out for it and see if i can reproduce it reliably.

**Comment by honeydrake** [comment] 2024-04-19 15:45
I've discovered it is also happening with Professional writ's (3 point professional awards you get from crafting quest turn ins) on multiple characters.  In the first shot, Blacksmith's Writ is missing from my bag and search.  But I know it's there because I just received it and it's sitting in my action bars where I link to my writs to find them easily. But then I /reload and it's now present. Screen Shots attached of before and after reload.
![Writ_missing](https://github.com/Cidan/BetterBags/assets/157518070/4b3298e1-8529-4caf-9d8b-86a16fb34bad)
![writ_present](https://github.com/Cidan/BetterBags/assets/157518070/d5c835cc-5439-4894-a447-678643f94432)

**Comment by Cidan** [comment] 2024-04-19 15:51
We believe we've nailed down why this is happening -- it's a subtle bug that goes away if you reduce your addon memory usage, i.e. disable addons. We have a fix coming, but it's going to take a few days longer as it requires a rework of some core systems.

I hope to have a fix out this weekend or early next week.

**Comment by honeydrake** [comment] 2024-04-19 16:04
Thank you for your hard work on this addon!

**Comment by honeydrake** [comment] 2024-05-06 18:33
Hi! This marked as complete but I am still having the same problem with the same type of items. For example, the quest rewards for completing a crafting weekly do not show up in my bag until I do a refresh. Missing before and present after refresh image proof attached.
![Missing_Scripts_5_6_24](https://github.com/Cidan/BetterBags/assets/157518070/e29c8c0d-e4a3-4451-a2b5-b0890d02442d)
![Present_Scripts_5_6_24](https://github.com/Cidan/BetterBags/assets/157518070/0ea01e79-a44a-4824-8b12-9499a4084b5f)

**Comment by honeydrake** [comment] 2024-05-06 23:05
I had 1.40 released 5/5 when I posted this morning. I've since upgraded to the release today of 1.42.  I haven't had a chance to see if it's still happening since 1.42. I'll let you know!

**Comment by Cidan** [comment] 2024-05-06 23:06
Okay, please do! And if you don't have it, install buggrabber and bugsack, which report Lua errors.

**Comment by zeptognome** [comment] 2024-08-02 08:43
Closing this as likely fixed with the numerous updates to the itemdata system since May. If this or a similar issue arises, plus do comment or raise a new issue @Frici42 or @honeydrake

**Closed by zeptognome** 2024-08-02 08:43 UTC
Labels: bug, triage
