### ISSUE TITLE
WotLK: "gear:" prefix not working with built-in equipment manager

### ISSUE THREAD

**Issue by fubar-coder** [Cidan/BetterBags#200] opened 2024-02-22 06:55 UTC
### Addon Version

v0.1.7

### World of Warcraft Version

Wrath

### Describe the bug

I am unable to find equipment sets when using the `gear:` prefix in the search.

### Steps to reproduce

1. Create two equipment sets `Tank`, and `Heal`
2. Equip the set `Heal`
3. Search for the `Tank` equipment set using the "gear:" prefix
4. I tried the search expressions `gear:tank`, and `gear:Tank`, partial names don't work either.

**Comment by Cidan** [comment] 2024-02-22 17:26
Duplicate of #179

**Closed by Cidan** 2024-02-22 17:26 UTC
Labels: bug, triage
