### ISSUE TITLE
[Feature]: Bag Search Improvement

### ISSUE THREAD

**Issue by stephenpierceio** [Cidan/BetterBags#323] opened 2024-04-10 20:37 UTC
### Describe the feature

Is it possible to have a search look at more than just the item titles? I find myself often looking for BOE items, or <Open> <Use> items. Apart from that, I imagine searching the descriptions would be helpful. Thanks for considering!

### Describe the implementation

Improve search logic of the betterbags search to look at the item title along with other key pieces of information.

**Comment by Cidan** [comment] 2024-04-10 20:39
Duplicate of #77

**Closed by Cidan** 2024-04-10 20:39 UTC
Labels: triage, feature
