### ISSUE TITLE
[Feature]: Free pocket spaces

### ISSUE THREAD

**Issue by Nora0204** [Cidan/BetterBags#508] opened 2024-07-31 07:34 UTC
### Describe the feature

Show free pocket spaces individually

### Describe the implementation

Show free pocket spaces individually like with Adibags, they are only displayed together

**Comment by zeptognome** [comment] 2024-07-31 09:48
unstacked free slots will be coming

duplicate of #373

**Closed by zeptognome** 2024-07-31 09:48 UTC
Labels: triage, feature
