### ISSUE TITLE
Pawn Upgrade Icon

### ISSUE THREAD

**Issue by MichaelPriebe** [Cidan/BetterBags#78] opened 2023-12-29 18:15 UTC
Would love to see support for showing the Pawn upgrade icon.

**Comment by radhaz** [comment] 2024-02-22 19:55
Just made an alt and enabled Pawn and I am not seeing the typical arrow notification on the tooltip while using BetterBags; however, the arrow is present in Adibags? I see the issue is marked complete so I'm wondering if it is my side/settings? Should I open a new issue since this is marked as completed?

BetterBags v.0.1.7
Pawn 2.8.9

**Comment by Cidan** [comment] 2024-02-22 20:27
Complete, not released. When this issue closes, it will be released.

**Closed** 2024-02-23 05:30 UTC
Labels: good first issue, triage
