### ISSUE TITLE
[Feature]: Able to search Inventory

### ISSUE THREAD

**Issue by Serverfrog** [Cidan/BetterBags#454] opened 2024-07-01 13:14 UTC
### Describe the feature

With #453 Implemented, it should be possible to search the Inventory or Inventories.
This would make it much easier to search for specific items over different Characters

### Describe the implementation

 - grey out everything in the current Bag, which not has the current search as Substring inside them (question is: only Name or also description?)
 - pop up another little window which contains a TextField on the Upper part and a List of all Items on the lower one, Then start listing all items with the substring inside them with the third character (so not all items of all characters needed to be shown)

**Comment by Cidan** [comment] 2024-07-02 05:30
Duplicate of #26

**Closed by Cidan** 2024-07-02 05:30 UTC
Labels: triage, feature
