### ISSUE TITLE
Stutter on every item pickup

### ISSUE THREAD

**Issue by Boymann** [Cidan/BetterBags#218] opened 2024-02-24 12:13 UTC
### Addon Version

v0.1.17

### World of Warcraft Version

Retail

### Describe the bug

Whenever an item is looted or bought from a vendor, the game stutters.

### Steps to reproduce

1. Have backpack open.
2. Loot or buy an item from a vendor.
3. Get annoying stutter

**Comment by Cidan** [comment] 2024-02-24 16:37
This has been fixed in the latest Alpha, duplicate of #146

**Closed by Cidan** 2024-02-24 16:37 UTC
Labels: bug, triage
