### ISSUE TITLE
Bank/Bag - List view Pawn Error

### ISSUE THREAD

**Issue by TuttiRH** [Cidan/BetterBags#235] opened 2024-02-25 13:22 UTC
### Addon Version

v0.1.8-2-gca2d17b

### World of Warcraft Version

Retail

### Describe the bug

Happens when switching the view to "List" in Bag/Bank

### Steps to reproduce

**Bank - List View Error**

2x BetterBags/integrations/pawn.lua:16: attempt to index field 'UpgradeIcon' (a nil value)
[string "@BetterBags/integrations/pawn.lua"]:16: in function <BetterBags/integrations/pawn.lua:13>
[string "@BetterBags/integrations/pawn.lua"]:36: in function `cb'
[string "@BetterBags/core/events.lua"]:45: in function <BetterBags/core/events.lua:40>
[string "=[C]"]: ?
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:138: in function `SendMessage'
[string "@BetterBags/frames/bag.lua"]:221: in function `Draw'
[string "@BetterBags/core/init.lua"]:146: in function `cb'
[string "@BetterBags/core/events.lua"]:45: in function <BetterBags/core/events.lua:40>
[string "=[C]"]: ?
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
...
[string "@BetterBags/data/items.lua"]:352: in function <BetterBags/data/items.lua:320>
[string "=[C]"]: in function `xpcall'
[string "@FrameXML/ObjectAPI/ContinuableContainer.lua"]:83: in function <..FrameXML/ObjectAPI/ContinuableContainer.lua:75>
[string "=(tail call)"]: ?
[string "@BetterBags/data/items.lua"]:320: in function `ProcessBankContainer'
[string "@BetterBags/data/items.lua"]:199: in function `RefreshBank'
[string "@BetterBags/data/items.lua"]:160: in function `DoRefreshAll'
[string "@BetterBags/data/items.lua"]:98: in function <BetterBags/data/items.lua:97>
[string "=[C]"]: in function `xpcall'
[string "@BetterBags/core/events.lua"]:115: in function <BetterBags/core/events.lua:110>

Locals:
item = <table> {
 rowButton = BetterBagsRowItemButton110 {
 }
 button = <table> {
 }
 text = FontString {
 }
 data = <table> {
 }
 frame = Frame {
 }
}
bagid = 12
slotid = 15
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'UpgradeIcon' (a nil value)"

**Bag - List View Error**

2x BetterBags/integrations/pawn.lua:18: attempt to index field 'UpgradeIcon' (a nil value)
[string "@BetterBags/integrations/pawn.lua"]:18: in function <BetterBags/integrations/pawn.lua:13>
[string "@BetterBags/integrations/pawn.lua"]:36: in function `cb'
[string "@BetterBags/core/events.lua"]:45: in function <BetterBags/core/events.lua:40>
[string "=[C]"]: ?
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:138: in function `SendMessage'
[string "@BetterBags/frames/bag.lua"]:221: in function `Draw'
[string "@BetterBags/core/init.lua"]:141: in function `cb'
[string "@BetterBags/core/events.lua"]:45: in function <BetterBags/core/events.lua:40>
[string "=[C]"]: ?
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:148: in function <BetterBags/core/events.lua:147>

Locals:
item = <table> {
 rowButton = BetterBagsRowItemButton131 {
 }
 button = <table> {
 }
 text = FontString {
 }
 data = <table> {
 }
 frame = Frame {
 }
}
bagid = 3
slotid = 25
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'UpgradeIcon' (a nil value)"

**Comment by Cidan** [comment] 2024-02-25 17:15
I can't reproduce this, and it also doesn't match up with the code, i.e. line 16 isn't the same as what the error message says -- did you by any chance forget to /reload after upgrading?

**Comment by TuttiRH** [comment] 2024-02-25 17:37
I just made a complete reinstall and the LUA Error is the same when i switch the view to "List" instead of "Section Grid".

Here is a screenshot which version im running on.
<img width="1467" alt="25-02-2024_18-34-02" src="https://github.com/Cidan/BetterBags/assets/3890415/676f38bb-62d1-4493-a4a7-51371bd50260">

**Comment by Cidan** [comment] 2024-02-25 18:11
so this is silly, but bugsack has a bug that shows you the wrong error messages sometimes if it has bugs from a previous error (even if you quit the game).

can you clear bugsack and trigger it again?

**Comment by Cidan** [comment] 2024-02-25 18:11
sorry, asking this, because the error isn't lining up with a valid line of code that has that error

**Comment by TuttiRH** [comment] 2024-02-25 18:16
I wiped the cache and all previous bug reports from BugSack.

Still getting the same Error.

1x BetterBags/integrations/pawn.lua:18: attempt to index field 'UpgradeIcon' (a nil value)
[string "@BetterBags/integrations/pawn.lua"]:18: in function <BetterBags/integrations/pawn.lua:13>
[string "@BetterBags/integrations/pawn.lua"]:36: in function `cb'
[string "@BetterBags/core/events.lua"]:45: in function <BetterBags/core/events.lua:40>
[string "=[C]"]: ?
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:138: in function `SendMessage'
[string "@BetterBags/frames/bag.lua"]:221: in function `Draw'
[string "@BetterBags/core/init.lua"]:141: in function `cb'
[string "@BetterBags/core/events.lua"]:45: in function <BetterBags/core/events.lua:40>
[string "=[C]"]: ?
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Tom/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@TomTom/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:148: in function <BetterBags/core/events.lua:147>

Locals:
item = <table> {
 rowButton = BetterBagsRowItemButton24 {
 }
 button = <table> {
 }
 text = FontString {
 }
 data = <table> {
 }
 frame = Frame {
 }
}
bagid = 3
slotid = 25
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'UpgradeIcon' (a nil value)"

**Comment by Cidan** [comment] 2024-02-25 18:30
Alright, I'm about to push another alpha soon. This makes no sense, because i literally check:

` if not item.button.UpgradeIcon then return end`

Let's see if it's fixed on the next version with some other changes i made.

**Comment by Cidan** [comment] 2024-02-25 20:52
Alright, new alpha has been pushed -- let me know if that fixes it!

**Comment by TuttiRH** [comment] 2024-02-26 14:58
This bug is gone with the latest alpha relese ([v0.1.8-3-g819b191).

**Closed** 2024-05-02 01:59 UTC
Labels: bug, triage
