### ISSUE TITLE
[Feature]: Custom background 

### ISSUE THREAD

**Issue by I-AM-T3X** [Cidan/BetterBags#153] opened 2024-02-19 22:11 UTC
### Describe the feature

Could you consider incorporating the custom background feature, similar to what's available in the Details addon, into Better Bags?

### Describe the implementation

dropping a TGA image into the interface folderand then have a spot in the settign to type in the files name and when reload and its there

**Comment by Cidan** [comment] 2024-02-21 04:16
Duplicate of #137

**Closed by Cidan** 2024-02-21 04:16 UTC
Labels: triage, feature
