### ISSUE TITLE
[Feature Request] Ammunition Handling

### ISSUE THREAD

**Issue by Silun** [Cidan/BetterBags#106] opened 2024-02-19 08:28 UTC
I would like to suggest a feature: Ammunition placement. Something along the lines of one of these options, perhaps:
- Make it possible to see ammunition that is not in the ammo bag, maybe make the icon red.
- Have a button that automatically sorts all ammunition into the ammo bag.
- Automatically sort ammo into the ammo bag whenever bags are opened or closed or something to that effect.
- Option to hide ammo from bags and maybe place a single ammo icon with the total amount of ammo left (per type) instead of 16x the same icon with 200 stacks

Currently, we have to switch to bag view to see their contents verbatim.

An adjacent issue is that free slots in ammo bags are counted towards the free inventory slots, which they probably should not, since only ammo can be put in them.

**Comment by Cidan** [comment] 2024-02-21 04:27
Duplicate of #159 #114

**Closed by Cidan** 2024-02-21 04:27 UTC
Labels: triage
