### ISSUE TITLE
Category titles persist after closing bag window

### ISSUE THREAD

**Issue by joao44289** [Cidan/BetterBags#354] opened 2024-05-02 17:11 UTC
### Addon Version

v0.1.33

### World of Warcraft Version

Retail

### Describe the bug

Sometimes after closing the bag window some category titles persist and only go away after a /reload. 
![bug](https://github.com/Cidan/BetterBags/assets/64077887/be443c6b-ef22-4c4a-b61d-013cf1d30ce8)

### Steps to reproduce

1. It seems to happen at random times so not sure what are the steps to reproduce it.

**Comment by Cidan** [comment] 2024-05-02 17:12
That's odd! I'll hunt this down and fix it asap.

**Comment by flo187dev** [comment] 2024-05-02 22:53
this happens to me as well with all category titles of bank bags. they stay after closing the bank and only a /reload will fix it. surprisingly the bug occurs even after disabling all other addons.

thanks for looking into this!

![image](https://github.com/Cidan/BetterBags/assets/32168750/4e6db2d8-566f-42f3-b6a5-b93bf36e597e)

**Comment by Cidan** [comment] 2024-05-02 23:03
I'm having a hard time reproducing this, but this part of the code was slated for a rewrite anyway.

If possible, can you detail the exact order in which you caused this to happen?

**Comment by flo187dev** [comment] 2024-05-02 23:18
my screenshot above only involves 2 steps:

1. Talk to Banker
2. Close Bank window

some other things I noticed:

* I've now deleted BetterBags.lua in SavedVariables but that didn't change anything.
* I don't use custom categories
* it never happens to the regular bags
* I've always had the issue at the bank since I started using BetterBags a couple of months ago. 
* It also doesn't matter if I try it after logging in or after hours of playing

**Comment by Cidan** [comment] 2024-05-02 23:20
> I've always had the issue at the bank since I started using BetterBags a couple of months ago.

This is a huge red flag for me, wow, I had no idea! I wish I could have helped with this sooner.

When you close the bank, do you hit the X button, or do you walk away? What exactly do you do to close the bank?

**Comment by flo187dev** [comment] 2024-05-02 23:23
> This is a huge red flag for me, wow, I had no idea! I wish I could have helped with this sooner.

I only mentioned it to narrow down the issue. :) as it is only when using the bank it didn't affect me too much and I figured it was because of early development.

I've now tried the X button, Escape key and walking way. Same results for all three.

**Comment by flo187dev** [comment] 2024-05-02 23:26
not sure if this info helps but the titles retain some (buggy) responsiveness like being clickable and showing a tooltip on hover:

![image](https://github.com/Cidan/BetterBags/assets/32168750/a77c5584-9d3f-4904-b619-ccd8801b5845)

**Comment by flo187dev** [comment] 2024-05-02 23:28
oh i found something! it seems to only happen when "Use UI Scale" is checked in System > Graphics.

![image](https://github.com/Cidan/BetterBags/assets/32168750/4bf2433e-6f26-4e9e-8da5-4a2e002aa0cd)

**Comment by flo187dev** [comment] 2024-05-02 23:43
some additional info:

so it only happens when enabling the checkbox AND using 100% scaling. The category headers behave normally with the checkbox disabled or on any other scaling factor, even 99% or 101%.

why do I check the box but keep the setting at 100%? well it does change the UI size compared to not checking it... I'm using a 3440x1440 high(-ish) DPI monitor so text & ui are a bit small when NOT checking the box.

**Comment by Cidan** [comment] 2024-05-03 00:41
wow! that's crazy -- i'll see if i can hunt this down later tonight

**Comment by Cidan** [comment] 2024-05-03 05:04
Alright, thanks to @zeptognome for the help, we fixed the bug. Putting out a release soon for this.

**Comment by Cidan** [comment] 2024-05-03 05:28
Some more info, we definitely think this is a bug in Blizzard's code, as I don't think this should have been happening as-is. We implemented a fix (thought admittedly, it's something we should have done all along) and is out in the latest alpha build.

**Comment by flo187dev** [comment] 2024-05-03 06:45
this fixed it for me regardless of scaling on/off or slider setting. thanks! :D

**Comment by Cidan** [comment] 2024-05-04 01:09
This has been fixed and deployed.

**Closed by Cidan** 2024-05-04 01:09 UTC
Labels: bug, triage
