### ISSUE TITLE
[Feature]: libDataBroker (ldb) support

### ISSUE THREAD

**Issue by zeptognome** [Cidan/BetterBags#152] opened 2024-02-19 21:49 UTC
### Describe the feature

Please add LibDataBroker support. Display should show empty bag slots at minimum.
Options to show reagent slots and/or total bag slots would be nice.

Adding some (or all) of the backpack context menu to the broker button would be great

### Describe the implementation

screenshot showing adibags ldb in the top center and a sample money broker for some inspiration

![image](https://github.com/Cidan/BetterBags/assets/158738380/6bde0e56-2ebb-4de8-8c87-befcd4bf9ab0)

**Comment by Cidan** [comment] 2024-02-19 21:52
Duplicate of #71

**Closed by Cidan** 2024-02-19 21:52 UTC
Labels: triage, feature
