### ISSUE TITLE
[Feature]: Search by ilvl

### ISSUE THREAD

**Issue by Porkepix** [Cidan/BetterBags#368] opened 2024-05-11 13:31 UTC
### Describe the feature

Items should be searchable by ilvl, this is something that existed and worked with AdiBags

### Describe the implementation

Search by ilvl by just writing an ilvl in the search field, as it was working in AdiBags. This is especially usefull to empty bags of old raids gear that lost their "new item" tag.

One could imagine more complex search expressions like ilvl: <200 ; ilvl ≥ 300 etc. but that would come with the implementation of complex search expressions (which could include search by category, piece of gear etc. etc.)

Get back at a simple search by writing the ilvl would already be a good first step.

**Comment by Cidan** [comment] 2024-05-11 15:02
Duplicate of #272

**Closed by Cidan** 2024-05-11 15:02 UTC
Labels: triage, feature
