### ISSUE TITLE
[Question]: Is it possible to show all available free slots?

### ISSUE THREAD

**Issue by tance77** [Cidan/BetterBags#486] opened 2024-07-27 00:26 UTC
### Describe the feature

Is it possible to show all available free slots instead of just one with a count?

### Describe the implementation

N/a 
N/a 
N/a 
N/a 
N/a 
N/a

**Comment by AMaribo** [comment] 2024-07-27 02:29
Duplicate of #373

**Closed by AMaribo** 2024-07-27 02:29 UTC
Labels: triage, feature
