### ISSUE TITLE
Some items doesn't show in keyring 

### ISSUE THREAD

**Issue by mrbuds** [Cidan/BetterBags#601] opened 2024-08-17 20:47 UTC
### Addon Version

v0.1.99

### World of Warcraft Version

Classic Era (And SoD/Hardcore)

### Describe the bug

I have some items that doesn't show in the by category view, but they show if i show bags

![image](https://github.com/user-attachments/assets/aa433b89-0b9d-4b77-bd50-9c4eb32593a9)

![image](https://github.com/user-attachments/assets/7bbfa593-bd4e-4d1c-8dd1-373b7599b65c)

itemIds: 221315, 228189, 227925, 227927

### Steps to reproduce

get items mentioned, show by category

**Comment by AMaribo** [comment] 2024-08-17 23:32
Duplicate of #469

**Closed by AMaribo** 2024-08-17 23:32 UTC
Labels: bug, triage
