### ISSUE TITLE
[Feature]: Lock Bag and Bank Positions

### ISSUE THREAD

**Issue by SargonStarblade** [Cidan/BetterBags#365] opened 2024-05-10 12:34 UTC
### Describe the feature

AdiBags had a feature that allowed you to lock the bag position and the bank could be locked to the edge of the bag. Right now I have to keep moving the bank around as I transfer items to my bags because the bag extends and winds up under the bank. AdiBags also allowed us to lock the bag position so it did not get accidentally moved.

### Describe the implementation

It would be great if the bank was able to be linked to the edge of the bags so that it moved as the bag was expanded and locking the bag position would also be great.

**Comment by Cidan** [comment] 2024-05-10 17:39
Duplicate of #305

**Closed by Cidan** 2024-05-10 17:39 UTC
Labels: triage, feature
