### ISSUE TITLE
[Feature]: Anchor, bag grow directions disable auto shrink (or whatever it is called)

### ISSUE THREAD

**Issue by SargonStarblade** [Cidan/BetterBags#459] opened 2024-07-04 03:55 UTC
### Describe the feature

I like to have my bags in the lower right of the screen, AdiBags had a function that let me set an anchor and the bags would grow out from that spot left and up. Currently I have to keep moving the bags as I add because the bags grow off screen. Additionally when removing items to the guild bank, bank, selling or auction house the bags shrink after a few items causing me to move or sell the wrong item because what I clicked on moved just before I clicked on it.

### Describe the implementation

For the anchor and grow, implement something along the lines of what AdiBags had. For the auto shrink give an option to manually shrink to get rid of empty spaces by either closing the bag and reopening and/or right clicking the bag button that currently clears the new item category.

**Comment by Cidan** [comment] 2024-07-04 03:59
Duplicate of #376

**Closed by Cidan** 2024-07-04 03:59 UTC
Labels: triage, feature

**Comment by Cidan** [comment] 2024-07-04 04:00
>  bags shrink after a few items causing me to move or sell the wrong item because what I clicked on moved just before I clicked on it.

This is a different issue, and should never happen when you purely remove items, but it does happen if you re-add items. This will change in the near future.
