### ISSUE TITLE
[Feature]: Ability to toggle categories

### ISSUE THREAD

**Issue by int3ro** [Cidan/BetterBags#142] opened 2024-02-19 20:02 UTC
### Describe the feature

I'd really love if I was able to click on a category header to collapse the contents of the category.

### Describe the implementation

When clicking on "Tradeskill" the contents of the category collapse and the header changes to "Tradeskill (13)" with an indication how many items (13) are hidden. When clicking again the contents should be visible again.

**Comment by Cidan** [comment] 2024-02-19 20:03
Duplicate of #104

**Closed by Cidan** 2024-02-19 20:03 UTC
Labels: triage, feature
