### ISSUE TITLE
[Feature]: empty quiver slots next to empty bag slots

### ISSUE THREAD

**Issue by Augry2** [Cidan/BetterBags#259] opened 2024-03-01 12:28 UTC
### Describe the feature

it would be great if betterbags had the feature to show how many empty projectile slots there are next to the window that shows how many empty bag slots there are like if you have a quiver or ammo bag equipped

### Describe the implementation

if a quiver or ammo pouch is equipped there should appear a new box that shows how many empty slots there are in the normal bags, and how many empty slots there are in the ammo bag

**Comment by Cidan** [comment] 2024-03-01 16:28
Duplicate of #159

**Closed by Cidan** 2024-03-01 16:28 UTC
Labels: triage, feature
