### ISSUE TITLE
[Feature]: Font customization

### ISSUE THREAD

**Issue by peoii** [Cidan/BetterBags#270] opened 2024-03-04 02:20 UTC
### Describe the feature

Allow users to choose the font for the following items, preferably individually:

* ilvl text
* Currencies
* Bag title text

While I realize it is superficial in nature, it allows it to better fit with the overall UI.  Perhaps this could be a part of the theming described in the readme as a planned feature, perhaps not, but figure best to document it as is.

### Describe the implementation

In options under each item (bag / bank) a series of options to configure any available font (even those from sharedmedia fonts) and potentially font size to accommodate fonts that use strange kerning.

**Comment by Cidan** [comment] 2024-03-04 02:22
Duplicate of #137

**Closed by Cidan** 2024-03-04 02:22 UTC
Labels: triage, feature
